DROP TABLE IF EXISTS page;

CREATE TABLE page (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT UNIQUE NOT NULL,
  title_id TEXT UNIQUE NOT NULL,
  content TEXT NOT NULL,
  date TEXT NOT NULL,
  tags TEXT NULL
);

